---
- name: Installing Apache2 Web-Server
  hosts: webservers
  become: true
  tasks:
  - name: Update 
    apt:
     update_cache: yes

  - name: Install Apache
    apt:
     name: apache2
     state: present

  - name: Ensure apache is running
    service:
     name: apache2
     state: started
     enabled: true    

  - name: Restart apache
    service:
     name: apache2
     state: restarted
